title: Anmol Sandhu
url: "https://anmol.dev"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes

sass:
    style: compressed
    sass_dir: _sass

collections:
  projects:
    output: true

nav:
    - name: "About"
      link: ""
    - name: "Resume"
      link: "resume.pdf"
    - name: "Projects"
      link: "projects"
    - name: "Contact"
      link: "contact"
